<form  id="signupForm" method="post" action="#">
        <fieldset>
            <legend>Validating a complete form</legend>
            <p>
                <label for="firstname">Firstname</label>
                <input id="firstname" name="firstname" type="text">
            </p>
            <p>
                <label for="lastname">Lastname</label>
                <input id="lastname" name="lastname" type="text">
            </p>
            <p>
                <label for="username">Username</label>
                <input id="username" name="username" type="text">
            </p>
            <p>
                <label for="password">Password</label>
                <input id="password" name="password" type="password">
            </p>
            <p>
                <label for="confirm_password">Confirm password</label>
                <input id="confirm_password" name="confirm_password" type="password">
            </p>
            <p>
                <label for="email">Email</label>
                <input id="email" name="email" type="email">
            </p>
            
            <p>
                <input class="submit" type="submit" value="Submit">
            </p>
        </fieldset>
    </form>